{% set name = "remi" %}
{% set version = "2020.11.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2a32658146b63d33a88aff7362679873c9df9e42a9e651c9e6642da834b3cca1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - setuptools

test:
  imports:
    - remi

about:
  home: https://github.com/dddomodossola/remi
  license: Apache 2.0
  license_family: Apache
  license_file: license.txt
  summary: Remi is a GUI library for Python applications that gets rendered in web browsers.
  doc_url: https://github.com/dddomodossola/remi
  dev_url: https://github.com/dddomodossola/remi

extra:
  recipe-maintainers:
    - silun
