{% set name = "remi" %}
{% set version = "2020.3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4cb8eee398502f547b1ea5cf19304ce46bdc537a29b79066fda3e5d05130fdc4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - remi

about:
  home: https://github.com/dddomodossola/remi
  license: Apache 2.0
  license_family: Apache
  license_file: license.txt
  summary: Remi is a GUI library for Python applications that gets rendered in web browsers.
  doc_url: https://github.com/dddomodossola/remi
  dev_url: https://github.com/dddomodossola/remi

extra:
  recipe-maintainers:
    - silun
