{% set name = "remi" %}
{% set version = "2022.7.27" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 542df88e174bbd58fe763c49e5c2116f2c8413c1a934731069ed8c17bb9cd64c

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - setuptools

test:
  requires:
    - python {{ python_min }}
  imports:
    - remi

about:
  home: https://github.com/dddomodossola/remi
  license: Apache-2.0
  license_family: Apache
  license_file: license.txt
  summary: Remi is a GUI library for Python applications that gets rendered in web browsers.
  doc_url: https://github.com/dddomodossola/remi
  dev_url: https://github.com/dddomodossola/remi

extra:
  recipe-maintainers:
    - silun
